# ---

- hosts: all
  become: yes
  remote_user: vagrant
  tasks:
  - name: Update package list
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes

  - name: install Some Needed Packages 
    apt:
      name: ['curl', 'cron', 'nano'] # install systemctl
      state: present

  - name: Install some python packages
    apt:
      name: ['python3-pip','python3-flask']   # install pwntools

  - name: Copy script file
    copy:
        src: /home/mahdi/Desktop/Mahdi/Mahdi/Projects/Vulnerable_Web_Server/script.sh
        dest: /home/vagrant/script.sh
        owner: vagrant
        group: vagrant
        mode: '0755'

  - name: Run Script file to create users
    command: bash /home/vagrant/script.sh

 